#port: /dev/ttyUSB3
port: /dev/ttyUSB0
baudrate: 38400
# Difference in pulse count between the mechanical and electrical origin
origin_offset: 180
# Distance between the centers of the front and rear wheels (meters)
wheelbase: 1.53
# Distance between the rear shaft and the body center (meters)
rear_shaft_to_body_center: 1.6
# Maximum rotation angle (in radians) and the corresponding pulse count
# Set to 630 degrees for both directions
limit_ccw: [ 10.9955742875643,  18154]
limit_cw:  [-10.9955742875643, -18714]
# How much the steering turns divided by how much the wheel turns
# Used to determine how much the steering should be rotated in order to achive
# a certain turning rate
steering_gear_ratio: 18.0
